include:
  - proxy.yaml

version: "3"

x-deploy: &deploy-dev
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: 512M
      reservations:
        memory: 256M
x-env_file: &env_file
  env_file:
    - .env

services:
  web:
    <<: [*deploy-dev, *env_file]
    build:
      dockerfile: Dockerfile.python
    image: web_app:latest
    networks:
      backend:
        ipv4_address: 172.20.0.5
    environment:
      - DB_NAME=${MYSQL_DATABASE}
      - DB_TABLE=${MYSQL_TABLE}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_USER=${MYSQL_USER}
      - DB_HOST=db
    ports:
      - "5000:5000"
    restart: always
    links:
      - db

  db:
    image: mariadb:10.6.4-focal
    <<: [*env_file]
    networks:
      backend:
        ipv4_address: 172.20.0.10
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_TABLE=${MYSQL_TABLE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%"
    restart: on-failure

  cron:
    image: schnitzler/mysqldump
    networks:
      backend:
        ipv4_address: 172.20.0.15
    volumes:
      #- /opt/bin/crontab:/var/spool/cron/crontabs/root
      - ./backup:/usr/local/bin/backup
    volumes_from:
      - backup
    command: ["-l", "8", "-d", "8"]
    environment:
      - MYSQL_HOST=172.20.0.10
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  backup:
    image: busybox
    networks:
      backend:
        ipv4_address: 172.20.0.20
    volumes:
      - ./backup:/backup
    restart: always

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
